[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
wee_alloc = "0.4"
rand = "0.8"  
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
getrandom = { version = "0.2.15", features = ["js"] }
js-sys = "0.3"

[lib]
crate-type = ["cdylib"]
